import '@/styles/globals.css'
import 'animate.css';
import {Montserrat} from 'next/font/google'
import Head from "next/head";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import {useRouter} from "next/router";
import {IntlProvider} from "react-intl";
import en from '../../language/en.json'
import pl from '../../language/pl.json'
import ua from '../../language/ua.json'

const messages = {
    en, pl, ua
}
const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-mont"
})
export default function App({Component, pageProps}) {
    const {locale} = useRouter()
    return (
        <>
            <IntlProvider locale={locale} messages={messages[locale]}>
                <Head>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <main className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}>

                    <NavBar/>
                    <Component {...pageProps} />
                    <Footer/>
                </main>
            </IntlProvider>
        </>
    )
}
